#title: AI Conference Deadlines
title: Mobile Systems/ Security Conference Deadlines
#description: Countdowns to top CV/NLP/ML/Robotics/AI conference deadlines
#author: Abhishek Das

domain: "https://msr95.github.io"
baseurl: ""

#twitter_hashtag: 
github_username: msr95
github_repo: msr95.github.io

markdown: kramdown
ga_id:

include: ['_pages']
